commentaires francois
pyomeca/ezc3d pull request #158
Opened 2020-10-05 14:49 UTC by fbailly

2020-10-05 21:16 UTC, pariterre requested changes

2020-10-05 21:16 UTC, pariterre commented on doc/paper/paper.md
> +While it would make sense to develop a portable solution once and for all, as offered by the standardized *c3d* format ($\leftarrow$ la solution portable c'est pour lire le *c3d*, pourquoi cette port
Parce que théoriquement ça devrait être ça. Dans les faits, le format n'est pas utilisé comme tel. Vois-tu une autre façon d'exprimer cela?

2020-10-06 08:53 UTC, fbailly commented on doc/paper/paper.md
> +While it would make sense to develop a portable solution once and for all, as offered by the standardized *c3d* format ($\leftarrow$ la solution portable c'est pour lire le *c3d*, pourquoi cette port
Il y a le format d'un côté (pas remis en question) et l'API de l'autre. La solution portable recherchée concerne l'API, correct ?

2020-10-06 14:48 UTC, pariterre approved these changes
LGTM!

2020-10-06 14:48 UTC, merged