MATLAB explanations
pyomeca/ezc3d pull request #288
Opened 2023-05-11 19:12 UTC by EveCharbie

2023-05-11 20:05 UTC, pariterre requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/288)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @EveCharbie)

___
*[`README.md` line 133 at r1](https://reviewable.io/reviews/pyomeca/ezc3d/288#-NVBPKv_1VDHzIlaRuJ1:-NVBPKva5q8Yecj6ELEU:b-p3ynyx) ([raw file](https://github.com/pyomeca/ezc3d/blob/51920b7c2064f99c15d4fb9f686a55859626ce48/README.md#L133)):*
> ```Markdown
> > `BINDER_MATLAB` If you want (`ON`) or not (`OFF`) to build the MATLAB binder. Default is `OFF`.
> > 
> > `MATLAB_ROOT_DIR` If `BINDER_MATLAB` is set to `ON` then this variable should point to the root path of MATLAB directory (something like /usr/local/MATLAB/R2018a). Please note that the MATLAB binder is based on MATLAB R2018a API and won't compile on earlier versions. This variable should be found automatically, except on Mac where the value should manually be set to the MATLAB in the App folder.
> ```

or "C:\Program Files\MATLAB\R2022b" (and maybe 2022b so we don't look too late haha!)
___
*[`README.md` line 143 at r1](https://reviewable.io/reviews/pyomeca/ezc3d/288#-NVBPezE-Ss6YsNTpSt6:-NVBPezE-Ss6YsNTpSt7:b-7d74sh) ([raw file](https://github.com/pyomeca/ezc3d/blob/51920b7c2064f99c15d4fb9f686a55859626ce48/README.md#L143)):*
> ```Markdown
> > `Octave_ezc3d_INSTALL_DIR` If `BINDER_OCTAVE` is set to `ON` then this variable should point to the path where you want to install EZC3D. Typically, you want this to be in `{MY DOCUMENTS}/Octave`, which is not the default location. The default value is the toolbox folder on root, i.e., `/toolbox`. Please note that if you leave the default value, you will probably need to grant administrator rights to the installer. 
> 
> *Fix for MATLAB*: There is a known issue with libstdc++.so.6 in MATLAB. To fix it, you need to copy the libstdc++.so.6 from your system to the MATLAB bin folder. For example, on Ubuntu 18.04, you can do the following:
> ```

There is a known issue with libstdc++.so.6 in MATLAB on Ubuntu


<!-- Sent from Reviewable.io -->

2023-05-12 20:52 UTC, EveCharbie reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/288)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @pariterre)

___
*[`README.md` line 133 at r1](https://reviewable.io/reviews/pyomeca/ezc3d/288#-NVBPKv_1VDHzIlaRuJ1:-NVGisddAckbYukzIa8f:b-896fix) ([raw file](https://github.com/pyomeca/ezc3d/blob/51920b7c2064f99c15d4fb9f686a55859626ce48/README.md#L133)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

or "C:\Program Files\MATLAB\R2022b" (and maybe 2022b so we don't look too late haha!)
</blockquote></details>

Done.
___
*[`README.md` line 143 at r1](https://reviewable.io/reviews/pyomeca/ezc3d/288#-NVBPezE-Ss6YsNTpSt6:-NVGiRai98RPV0tIGtWg:b-896fix) ([raw file](https://github.com/pyomeca/ezc3d/blob/51920b7c2064f99c15d4fb9f686a55859626ce48/README.md#L143)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

There is a known issue with libstdc++.so.6 in MATLAB on Ubuntu
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-26 11:27 UTC, EveCharbie reviewed
@pariterre up :)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/288#-:-NWMnwBl2cH0HNgtXpbf:bsrikkl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2023-05-26 13:03 UTC, pariterre approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2023-05-26 13:03 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/288#-:-NWN9-_N5ng2T0s-4iUc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2023-05-26 15:11 UTC, merged